@fringaleAPI_HostAddress = https://localhost:7073

GET {{fringaleAPI_HostAddress}}/Plats

###


GET {{fringaleAPI_HostAddress}}/Plats/1

###


GET {{fringaleAPI_HostAddress}}/Plats

###


@id_pl=2
DELETE {{fringaleAPI_HostAddress}}/Plats/{id}?id_pl={{id_pl}}

###


